### ISSUE TITLE
install with composer

### ISSUE THREAD

**Issue by StephanKrauss** [Orange-Management/Documentor#14]
Hello,

is there a way to install the documentor with composer ?

Your sincerly

Stephan

**Comment by spl1nes** [comment]
Well there is a way now. However I cannot recommend to use it for any other projects. 

1. The current implementation is with certain assumptions in mind which will most likely not work for any other projects.
2. The current licensing model doesn't allow it.

```
    {
        "repositories": [
            {
                "type": "vcs",
                "url": "https://github.com/Orange-Management/Documentor.git"
            },
            {
                "type": "vcs",
                "url": "https://github.com/Orange-Management/phpOMS.git"
            }
        ],
        "require": {
            "Orange-Management/phpOMS": "dev-master",
            "Orange-Management/Documentor": "dev-master"
        }
    }
```
